- name: Install requirements
  become: yes
  apt:
      name: ['jq']
      state: present

- name: Check if daemon.json exists
  become: yes
  stat: path=/etc/docker/daemon.json
  register: daemon_json

- name: Create empty docker configuration file if it does not exist
  become: yes
  template:
      src: etc/docker/daemon.json
      dest: /etc/docker/daemon.json
  when: not daemon_json.stat.exists

- name: Read daemon.json
  shell: cat /etc/docker/daemon.json
  register: daemon

- name: Configure docker daemon "json-file" logger only when selected
  become: yes
  command: "{{ item }}"
  with_items:
      - 'jq ".\"log-opts\".\"max-file\"=\"{{ docker_max_log_files }}\"" "/etc/docker/daemon.json" > /etc/docker/daemon.json'
      - 'jq ".\"log-opts\".\"max-size\"=\"{{ docker_max_log_size }}\"" "/etc/docker/daemon.json" > /etc/docker/daemon.json'
  when: daemon.stdout.find('"log-driver": "json-file"') != -1

- name: Configure docker daemon "local" logger only when selected
  become: yes
  command: "{{ item }}"
  with_items:
      - 'jq ".\"log-opts\".\"max-size\"=\"{{ docker_max_log_size }}\"" "/etc/docker/daemon.json" > /etc/docker/daemon.json'
  when: daemon.stdout.find('"log-driver": "local"') != -1
