- name: Make sure the journald.conf.d exists
  become: yes
  file:
      path: /etc/systemd/journald.conf.d/
      state: directory

- name: Configure systemd journal max. disk usage
  become: yes
  template:
      src: etc/systemd/journald.conf.d/org.riotkit.journal.conf.j2
      dest: /etc/systemd/journald.conf.d/org.riotkit.logs.conf
